
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ACTION NAME PATH SYS TYPE\n    command : ACTION type\n    \n    type :  TYPE NAME\n        |   TYPE PATH\n    command : SYS'
    
_lr_action_items = {'ACTION':([0,],[2,]),'SYS':([0,],[3,]),'$end':([1,3,4,6,7,],[0,-4,-1,-2,-3,]),'TYPE':([2,],[5,]),'NAME':([5,],[6,]),'PATH':([5,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[1,]),'type':([2,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> ACTION type','command',2,'p_command','main.py',50),
  ('type -> TYPE NAME','type',2,'p_type','main.py',57),
  ('type -> TYPE PATH','type',2,'p_type','main.py',58),
  ('command -> SYS','command',1,'p_sys','main.py',69),
]
